version: "3.8"

services:
  app:
    container_name: food-truck-picker-application
    build:
      context: .
    restart: always
    ports:
      - "4000:4000"
    command: /bin/sh start_app.sh
    depends_on:
      - database
  database:
    container_name: db-postgres-ftpicker
    image: postgres:16.0-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=food_truck_picker_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
